version: "3.8"
services:
  db:
    image: mysql:8.0.33
    restart: always
    volumes:
      - /data/db:/var/lib/postgresql/data
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: "billtime"
      MYSQL_ROOT_PASSWORD: "password"
volumes:
  db:
    driver: local