apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: billtime-server-network-policy
spec:
  podSelector:
    matchLabels:
      app: billtime-server
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 80
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: mysql
    ports:
    - protocol: TCP
      port: 3306