name: Nightly Teardown

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  teardown-with-terraform:
    runs-on: ubuntu-latest

    permissions:
      # Required by AWS login
      id-token: write 
      contents: read 
    
    defaults:
      run:
        working-directory: ./infrastructure/tf

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::436795273900:role/github-actions-billtime-terraform-backend
          aws-region: eu-west-2

      - name: Initialize Terraform
        run: terraform init
      
      - name: Select Terraform Workspace
        run: terraform workspace select staging

      - name: Apply Terraform plan
        run: terraform apply -destroy -auto-approve