name: Terraform Plan

on:
  pull_request:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    permissions:
      # required by Post Plan to GitHub PR
      pull-requests: write
      # Required by AWS login
      id-token: write 
      contents: read 
    
    defaults:
      run:
        working-directory: ./infrastructure/tf
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::436795273900:role/github-actions-billtime-terraform-backend
          aws-region: eu-west-2

      - name: Initialize Terraform
        run: terraform init

      - name: Select Terraform Workspace
        run: terraform workspace select staging

      - name: Terraform plan
        id: plan
        run: terraform plan -out=tfplan -var="do_token=${secrets.DO_TOKEN}" -no-color
      
      - name: Upload Terraform plan artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan-${{ github.sha }}
          path: infrastructure/tf/tfplan
          retention-days: 1     

      - name: Post Plan to GitHub PR
        uses: mshick/add-pr-comment@v2
        with:
          allow-repeats: true
          message: |
            ## Terraform plan
            ```
            ${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}
            ```  