name: Terraform Plan

on:
  pull_request:
env:
  AWS_REGION : "eu-west-2"
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure/tf
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::436795273900:role/github-actions-billtime-terraform-backend
          aws-region: eu-west-2

      - name: Initialize Terraform
        run: terraform init

      - name: Select Terraform Workspace
        run: terraform workspace select staging

      - name: Terraform plan
        run: terraform plan -out=tfplan -var="do_token=${DO_TOKEN}"
      
      - name: Upload Terraform plan artifact
        uses: actions/upload-artifact@v2
        run:
          working-directory: .
        with:
          name: terraform-plan
          path: tfplan